# Generated by Django 4.0.3 on 2022-03-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_userdata_0'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData_0',
        ),
    ]
